### ISSUE TITLE
Any plans to port to .Net Core?

### ISSUE THREAD

**Issue by ericgreenmix** [vytautask/Hangfire.PostgreSql#2]

**Comment by vytautask** [comment]
Currently we have dependencies on Dapper, Hangfire.Core and Npgsql, all of which have released/will release soon .net core versions. After that, and ~1 month (those packages will be really stable), I guess it could be ported to .net core. 

As the majority of the code is quite simple I believe there will be no issues to port it besides said dependencies. 

I have no specific date when I could do so as I am busy with other projects. 1 month from now is feasible.

**Comment by vytautask** [comment]
On original repo (frankhommers/Hangfire.PostgreSql) will be ready soon. The issue - https://github.com/frankhommers/Hangfire.PostgreSql/issues/34
