### ISSUE TITLE
Error while executing install/upgrade

### ISSUE THREAD

**Issue by towts** [vytautask/Hangfire.PostgreSql#4]
Seeing this error pop up in my logs from time to time.
Doesn't seem to be a big deal.

It appears as though this case is being singled out in the code but the if check may be failing to catch proper. It seems to want to avoid logging this error.

See PostgresSqlObjectInstaller.cs line 72

execute bumpVersionSql

```
catch (NpgsqlException ex)
{
//if exception message don't contain version applied, then we wanna know about error. other wise we're okay
    if ((ex.Message ?? "") != "version-already-applied") 
    {
           throw;
    }
}
```

But we seem to be fail that if check and hitting the throw and thus end up here. Seems the check on ex.Message should be more of a contains string check perhaps.
```
catch (Exception ex)
				{
					if (ex.Source.Equals("Npgsql"))
					{
						Log.ErrorException("Error while executing install/upgrade", ex);
					}

					scriptFound = false;
				}
```

Error while executing install/upgrade Npgsql.PostgresException (0x80004005): P0001: _**version-already-applied**_ at Npgsql.NpgsqlConnector.DoReadMessage(DataRowLoadingMode dataRowLoadingMode, Boolean isPrependedMessage) at Npgsql.NpgsqlConnector.ReadMessageWithPrepended(DataRowLoadingMode dataRowLoadingMode) at Npgsql.NpgsqlDataReader.NextResultInternal() at Npgsql.NpgsqlDataReader.NextResult() at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior) at Npgsql.NpgsqlCommand.ExecuteNonQueryInternal() at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)

**Comment by vytautask** [comment]
Thanks for reporting! I will see what I can do to fix this.

**Comment by vytautask** [comment]
I believe I have fixed issue in the new release. Let me know if everything's OK.
Thanks again for reporting!
